[package]
name = "audio_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
hound = "3.5.1"
log = "0.4.27"
rtrb = "0.3.2"
transport = { path = "../transport" }
uuid = { version = "1.17.0", features = ["v4"] }

[lints]
workspace = true
